/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_EDIT_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_1 (GUI_ID_USER + 0x03)
#define ID_BUTTON_2 (GUI_ID_USER + 0x04)
#define ID_BUTTON_3 (GUI_ID_USER + 0x05)
#define ID_BUTTON_4 (GUI_ID_USER + 0x06)
#define ID_BUTTON_5 (GUI_ID_USER + 0x07)
#define ID_BUTTON_6 (GUI_ID_USER + 0x08)
#define ID_BUTTON_7 (GUI_ID_USER + 0x09)
#define ID_BUTTON_8 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_9 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_10 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_11 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_12 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_13 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_14 (GUI_ID_USER + 0x10)
#define ID_BUTTON_15 (GUI_ID_USER + 0x11)
#define ID_BUTTON_16 (GUI_ID_USER + 0x12)
#define ID_BUTTON_17 (GUI_ID_USER + 0x13)
#define ID_TEXT_0 (GUI_ID_USER + 0x14)


// USER START (Optionally insert additional defines)
#include "main.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 113, 6, 248, 33, 0, 0xc8, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_0, 20, 50, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_1, 20, 90, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_2, 20, 130, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_3, 20, 170, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "1", ID_BUTTON_4, 100, 50, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_5, 100, 90, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_6, 100, 130, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ".", ID_BUTTON_7, 100, 170, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_8, 182, 50, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_9, 180, 90, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_10, 180, 130, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "00", ID_BUTTON_11, 180, 170, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "+", ID_BUTTON_12, 260, 50, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "-", ID_BUTTON_13, 260, 90, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "*", ID_BUTTON_14, 260, 130, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "/", ID_BUTTON_15, 260, 170, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Clear", ID_BUTTON_16, 340, 50, 80, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "=", ID_BUTTON_17, 340, 130, 80, 80, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "NTUST", ID_TEXT_0, 192, 230, 248, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
	
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  // USER START (Optionally insert additional variables)
	uint8_t value[20];
	static double  number;
	static double  num1;
	static double  num2;
	static int			touch=0;
	static char		buffer[20]="0";
	static int 		clear=0;
	static int 		equal=0;
	static int 		again=0;
	static int 		process=0;
	static int 		zero_bug=0;
	char* find_dot;
	char *
 _gcvt (double value, int ndigits, char *buf);
  // USER END
	find_dot = buffer;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00000000));
    EDIT_SetFont(hItem, GUI_FONT_32_1);
    //
    // Initialization of 'NTUST'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem,"NTUST Credit:B10702224");
    //EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
		TEXT_SetTextAlign(hItem, GUI_TA_CENTER);
    TEXT_SetFont(hItem, GUI_FONT_24_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
		sprintf(value,"%s",buffer);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, value);
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by '0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}
					if(!touch){
						if(buffer[0]=='0') memset( buffer, '\0', 20 );
						strcat(buffer,"0");
						num1 = strtod(buffer, NULL);
					}
					else{
						zero_bug=1;
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0') memset( buffer, '\0', 20 );
						strcat(buffer,"0");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}			
					if(!touch){
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"3");
						num1 = strtod(buffer, NULL);
					}
					else{
						zero_bug=1;
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"3");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}				
					if(!touch){
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"6");
						num1 = strtod(buffer, NULL);
					}
					else{
						zero_bug=1;
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"6");
						num2 = strtod(buffer, NULL);
					}	
				// USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}
					if(!touch){
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"9");
						num1 = strtod(buffer, NULL);
					}
					else{
						zero_bug=1;
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"9");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by '1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}
					if(!touch){
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"1");
						num1 = strtod(buffer, NULL);
					}
					else{
						zero_bug=1;
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"1");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}
					if(!touch){
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"4");
						num1 = strtod(buffer, NULL);
					}
					else{
						zero_bug=1;
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"4");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}
					if(!touch){
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"7");
						num1 = strtod(buffer, NULL);
					}
					else{
						zero_bug=1;
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"7");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by '.'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					find_dot = strchr (buffer, '.');
					if(!touch){
						if(!find_dot)strcat(buffer,".");
						num1 = strtod(buffer, NULL);
					}
					else{
						if(!find_dot)strcat(buffer,".");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by '2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}
					if(!touch){
						zero_bug=1;
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"2");
						num1 = strtod(buffer, NULL);
					}
					else{
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"2");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by '5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}
					if(!touch){
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"5");
						num1 = strtod(buffer, NULL);
					}
					else{
						zero_bug=1;
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"5");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by '8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}
					if(!touch){
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"8");
						num1 = strtod(buffer, NULL);
					}
					else{
						zero_bug=1;
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"8");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by '00'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					if(again){
						again=0;
						memset( buffer, '\0', 20 );
					}
					if(!touch){
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"00");
						num1 = strtod(buffer, NULL);
					}
					else{
						zero_bug=1;
						if(!clear){
							memset( buffer, '\0', 20 );
							clear=1;
						}
						if(buffer[0]=='0' && buffer[1]!='.') memset( buffer, '\0', 20 );
						strcat(buffer,"00");
						num2 = strtod(buffer, NULL);
					}	
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by '+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					process=1;
					touch=1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_13: // Notifications sent by '-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
						process=2;	
						touch=1;			
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_14: // Notifications sent by '*'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					process=3;
					touch=1;
				// USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_15: // Notifications sent by '/'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					process=4;
					touch=1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_16: // Notifications sent by 'Clear'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				memset( buffer, '\0', 20 );
			  memset( buffer, '0', 1 );
				num1=0;
				num2=0;
			  number=0;
				touch=0;
				clear=0;
				process=0;
				zero_bug=0;
			// USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_17: // Notifications sent by '='
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				switch(process){
					case 0 :
									number=0;
									break;
					case 1 :
									number=num1+num2;
									break;
					case 2 :
									number=num1-num2;
									break;
					case 3 :
									number=num1*num2;
									break;
					case 4 :
									number=num1/num2;
									break;
				}
				
				if (!zero_bug)
					sprintf (buffer, "0");
				else if(process == 4 && num2==0)
					sprintf (buffer, "error");
				else
					_gcvt(number,10,buffer);
				zero_bug=0;
				again=1;
				num1=0;
				num2=0;
			  number=0;
				touch=0;
				clear=0;
				process=0;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
char *
 _gcvt (double value, int ndigits, char *buf)
 {
   char *p = buf;
	 int i=0;
	 int dot=0;
	 int index;
   sprintf (buf, "%-#.*f", ndigits, value);
 
   /* It seems they expect us to return .XXXX instead of 0.XXXX  */
   if (*p == '-')
     p++;
   /*if (*p == '0' && p[1] == '.')
     memmove (p, p + 1, strlen (p + 1) + 1);*/
 
   /* They want Xe-YY, not X.e-YY, and XXXX instead of XXXX.  */
   p = strchr (buf, 'e');
   if (!p)
     {
       p = buf + strlen (buf);
       /* They don't want trailing zeroes.  */
       while (p[-1] == '0' && p > buf + 2)
			 *--p = '\0';
			 
     }
   if (p > buf && p[-1] == '.')
     memmove (p - 1, p, strlen (p) + 1);
	 
	p=buf;
	 for(i=0;i<10;i++){
		 if(*p=='\0'){
			index=i;
		 }
		 else
			p++;
		 
		 if(*p=='.') dot=1;
	 }
	 
	 if(index==9){
		 *p='\0';
	 }
	 else{
		 p=buf+i;
		 if((*p>52) && dot){
		    *(p-1)=*(p-1)+1;
		 }
		 *p='\0';
	 }

   return buf;
 }
// USER END

/*************************** End of file ****************************/
